### ISSUE TITLE
Crashes if public node unavailable

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/turtle-wallet-go#11]
should fail verbosely and gracefully and provide a fallback option, like launching a local daemon.

**Comment by woodyjon** [comment]
I cannot reproduce crashes. Is it possible your crash was caused by the network problem yesterday? Or tell me how if you can reproduce it easily.

When I have a wrong remote address or not responding remote node, in nest, syncing is just stuck. I'll improve that with a warning message saying the remote node might be down and propose to switch to local.

**Comment by woodyjon** [comment]
0a4a20d

**Comment by woodyjon** [comment]
OK, I see now, thanks to the logs. That crash is from something different (not related to the status of the node). I just fixed it here: 292025a
Will be included in the next release.

**Comment by RocksteadyTC** [comment]
Thanks :)
