### ISSUE TITLE
[Newbie question] It is possible to use Turtle without sync all blockchain ?

### ISSUE THREAD

**Issue by onliniak** [turtlecoin/turtle-wallet-go#21]
I use Etherwall in thin mode and here I doesn't sync anything after start wallet. 
In Turtle I have to sync all data with remote public node, why ?

It is possible to implement similar functionality in your wallet ?
Mainly because #18 (If I hibernate/suspend linux or close wallet, they don't save synced blocks. Save works only in CLI mode.)

**Comment by woodyjon** [comment]
If you use Nest with the option "remote node" selected at the top right of the welcome screen, Nest does not sync nor download the blockchain. What it has to do, however, is scan the blockchain to check if there are transactions related to your wallet. It can take a few hours, but much less than downloading the whole blockchain. And it is much longer than in ethereum due to the way the transactions are made in TurtleCoin.

But if there is no crash, closing the wallet or closing Nest must save the wallet sync. Could you please confirm if this is not the case?

Next version of Nest will have https://github.com/turtlecoin/turtle-wallet-go/issues/18

**Comment by woodyjon** [comment]
b8a28f5a042c08f26fbf67db469bd6c8c1847421
