### ISSUE TITLE
iswallet running needs more logic

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtle-wallet-go#3]
https://github.com/turtlecoin/turtle-wallet-go/blob/d8013e067618c7d391de6d063fa1925e386c9dd0/walletdmanager/walletdmanager.go#L586

hmm,

this app shouldn't care if other walletd's or turtlecoind's are running that have nothing to do with it.

I'm running two turtlecoind's on  my laptop and selected "remote node" as the one to use. so there is nothing in the way for this app to do its thing.

**Comment by woodyjon** [comment]
The reason I put it like this is because it sometimes has problems quitting walletd. So when users reload it, there are issues for opening the right wallet. And like so I can tell them to quit walletd manually. But for turtlecoind you're probably right, I will make more tests to see if there are issues if turtlecoind is already running.

**Comment by woodyjon** [comment]
Would you think this would be appropriate:
if local
    error if walletd or turtlecoind is open
else // remote node
   error only if walletd is open

**Comment by woodyjon** [comment]
above logic implemented in 0.20
