### ISSUE TITLE
Main page does not fully fit in the window

### ISSUE THREAD

**Issue by abiteofdust** [turtlecoin/turtle-wallet-go#30]
The "show transactions" switch and wallet syncing info are not visible without scrolling down. Perhaps this is due to the small resolution of my screen. For the new user it's not obvious that there is some info below. Personally I and one other person from discord encountered this.

It would be nice to make everything fit in the window on this resolution if possible. Or to add visible vertical window scrollbar.

* My OS: Windows 10 x64
* Screen resolution: 1366x768
* Wallet version: 0.30
* Using wallet in fullscreen mode

**Before scroll**
![shot1](https://user-images.githubusercontent.com/42123397/43690793-0c959c34-9919-11e8-919f-7e15d4193a27.png)

**After scroll**
![shot2](https://user-images.githubusercontent.com/42123397/43690794-0f34ce88-9919-11e8-8014-eebc2bd2155b.png)

**Comment by woodyjon** [comment]
Thanks. I just added a scroll bar, because the problem with making the height smaller is that it is not only the 768 pixels, it is also the size of the bottom bar and the size of the top bar, which defer among os' and among users.
Please check the scroll bar when the next version is released and tell me if you think it helps and is enough.

**Comment by abiteofdust** [comment]
That's great! Sure I will give feedback on new version when it comes out.

**Comment by abiteofdust** [comment]
Good. It definitely helps. I think that's enough.

**Comment by woodyjon** [comment]
Cool. Thanks
