### ISSUE TITLE
New walletd.exe 0.4.3 crashes on Win8x64

### ISSUE THREAD

**Issue by aleqx** [turtlecoin/turtle-wallet-go#8]
As subj says. Not sure if I'm the only one. These are the released binaries (I didn't compile it myself).

**Comment by woodyjon** [comment]
I am sorry but I cannot really do much if walletd crashes. But if walletd 0.4.2 was working for you, you can just take walletd 0.4.2 from https://github.com/turtlecoin/turtlecoin/releases and put it in the Nest folder instead of the provided walletd.
Otherwise, you'll have to compile walletd yourself.
I never tried Nest or walletd on win8, so please keep me posted.

**Comment by woodyjon** [comment]
I see your issue in the turtlecoin repo, I guess your issue here was a mistake. Can I close?

**Comment by aleqx** [comment]
I posted in both because both crash (both Nest and turtlecoin)

**Comment by woodyjon** [comment]
I close as that problem (with older processors) is known and will be fixed in the next turtlecoin release: https://github.com/turtlecoin/turtlecoin/issues/177
A new version of Nest will be released as soon as walletd new version is released.
In the meantime, if others have the same issue, please use walletd 0.4.2.
